apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailing-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailing
  template:
    metadata:
      labels:
        app: mailing
    spec:
      containers:
        - name: mailing
          image: jamesgoytia/ticketing-mailing
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-access-key
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret-access-key
                  key: AWS_SECRET_ACCESS_KEY
